intro-banner = "long"
prompt = ">>> "
pretty-print = "auto"
color = "auto"

[exchange-rates]
fetching-policy = "on-startup"

# https://github.com/sharkdp/numbat/issues/775
[formatting]
digit-separator = ","
